### ISSUE TITLE
Compile to project

### ISSUE THREAD

**Issue by unthoiz** [Hotride/UOPatcher#1]
Hello, I have a question regarding the compilation of this project. Is the latest version compiled with C ++ Builder? The code has thrown me some errors that do not come solve. 

[bcc32 Error] MainScript.cpp(137): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(81): parsing: void _fastcall TPatcher::FormCreate(TObject *)
[bcc32 Error] MainScript.cpp(137): E2342 Type mismatch in parameter 'lpLibFileName' (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(81): parsing: void _fastcall TPatcher::FormCreate(TObject *)
[bcc32 Warning] MainScript.cpp(174): W8004 'obj' is assigned a value that is never used
  Full parser context
    MainScript.cpp(165): parsing: void _fastcall TPatcher::lb_OrionGitHubClick(TObject *)
[bcc32 Warning] MainScript.cpp(247): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(247): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(247): E2342 Type mismatch in parameter 'lpClassName' (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Warning] MainScript.cpp(255): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(255): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(255): E2342 Type mismatch in parameter 'lpText' (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Warning] MainScript.cpp(378): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(378): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Error] MainScript.cpp(378): E2342 Type mismatch in parameter 'lpClassName' (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(236): parsing: void _fastcall TPatcher::lb_ClientListClick(TObject *)
[bcc32 Warning] MainScript.cpp(392): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(386): parsing: void _fastcall TPatcher::RuntimePatchClickProc(TObject *)
[bcc32 Error] MainScript.cpp(392): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(386): parsing: void _fastcall TPatcher::RuntimePatchClickProc(TObject *)
[bcc32 Error] MainScript.cpp(392): E2342 Type mismatch in parameter 'lpClassName' (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(386): parsing: void _fastcall TPatcher::RuntimePatchClickProc(TObject *)
[bcc32 Warning] MainScript.cpp(404): W8004 'hwnd' is assigned a value that is never used
  Full parser context
    MainScript.cpp(386): parsing: void _fastcall TPatcher::RuntimePatchClickProc(TObject *)
[bcc32 Warning] MainScript.cpp(448): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(438): parsing: void _fastcall TPatcher::img_RefreshFilePatchesClick(TObject *)
[bcc32 Error] MainScript.cpp(448): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(438): parsing: void _fastcall TPatcher::img_RefreshFilePatchesClick(TObject *)
[bcc32 Error] MainScript.cpp(448): E2340 Type mismatch in parameter 1 (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(438): parsing: void _fastcall TPatcher::img_RefreshFilePatchesClick(TObject *)
[bcc32 Warning] MainScript.cpp(482): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)
[bcc32 Error] MainScript.cpp(482): E2034 Cannot convert 'wchar_t *' to 'const char *'
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)
[bcc32 Error] MainScript.cpp(482): E2340 Type mismatch in parameter 1 (wanted 'const char *', got 'wchar_t *')
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)
[bcc32 Warning] MainScript.cpp(512): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)
[bcc32 Warning] MainScript.cpp(515): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)
[bcc32 Warning] MainScript.cpp(517): W8111 Accessing deprecated entity 'UnicodeString::t_str() const' 
  Full parser context
    MainScript.cpp(464): parsing: void _fastcall TPatcher::bt_ClientPatchClick(TObject *)

Greetings and thanks

**Comment by Hotride** [comment]
You must use RAD Studio 2010.
